# Generated by Django 4.2.6 on 2023-12-08 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="dept",
            fields=[
                ("deptno", models.IntegerField(primary_key=True, serialize=False)),
                ("dname", models.CharField(max_length=100)),
                ("loc", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="salgrade",
            fields=[
                ("hisal", models.IntegerField(primary_key=True, serialize=False)),
                ("losal", models.CharField(max_length=100)),
                ("grade", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="emp",
            fields=[
                ("empno", models.IntegerField(primary_key=True, serialize=False)),
                ("ename", models.CharField(max_length=100)),
                ("sal", models.IntegerField()),
                ("comm", models.IntegerField()),
                ("dname", models.CharField(max_length=100)),
                ("hiredate", models.DateField()),
                ("mgr", models.CharField(max_length=100)),
                (
                    "deptno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dept"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="bonus",
            fields=[
                ("sal", models.IntegerField(primary_key=True, serialize=False)),
                ("comm", models.CharField(max_length=100, null=True)),
                ("job", models.CharField(max_length=100)),
                (
                    "ename",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.emp"
                    ),
                ),
            ],
        ),
    ]
